sudo: true
file_glob: true

env:
 global:
  - SLACK=$SLACK_KEY

addons:
 chrome: stable

language: node_js
node_js:
 - "stable"

cache:
 directories:
  - "node_modules"

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 5 # give xvfb some time to start

script:
 - echo $SLACK_KEY
 - echo $SLACK
 - npm run smoke-test-gs-chrome

notifications:
 email: false
 slack: solocoders:echo $SLACK_KEY
 on_success: always
 on_failure: always