addons:
 chrome: stable

 language: node_js
node_js:
 - "stable"

cache:
 directories:
  - "node_modules"

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script:
 - npm run smoke-test-stage-chrome

notification:
 email: false