sudo: true
file_glob: true

addons:
 chrome: stable

language: node_js
node_js:
 - "stable"

cache:
 directories:
  - "node_modules"

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 5 # give xvfb some time to start
 - "bash test.sh"
 - "export SLACK_KEY"
 - "printenv | grep SLACK_KEY"

script:
 - npm run smoke-test-gs-chrome

notifications:
 email: false
 slack: "solocoders:SLACK_KEY"
 on_success: always
 on_failure: always